'' Color theme for PlantUML
''

!$THEME = "u"

skinparam useBetaStyle true

''
'' Colors taken from the css file of the BS theme
''
!$PRIMARY0050 = "#DFF4F7"
!$PRIMARY0100 = "#C0E9EF"
!$PRIMARY0200 = "#95D3DC"
!$PRIMARY0300 = "#6DBDC9"
!$PRIMARY0400 = "#46A7B6"
!$PRIMARY0500 = "#2291A2"
!$PRIMARY0600 = "#007C8F" /' <- '/
!$PRIMARY0700 = "#016372"
!$PRIMARY0800 = "#014954"
!$PRIMARY0900 = "#003037"
!$PRIMARY1000 = "#001619"

!$SECONDARY0050 = "#E9F9F7"
!$SECONDARY0100 = "#D4F3F0"
!$SECONDARY0200 = "#B1E2DD"
!$SECONDARY0300 = "#8ED0C9"
!$SECONDARY0400 = "#6BBFB6" /' <- '/
!$SECONDARY0500 = "#54A39B"
!$SECONDARY0600 = "#3C8880"
!$SECONDARY0700 = "#256C65"
!$SECONDARY0800 = "#12514A"
!$SECONDARY0900 = "#063530"
!$SECONDARY1000 = "#001917"

!$TERNARY0050 = "#DEF6FE"
!$TERNARY0100 = "#BDEDFD"
!$TERNARY0200 = "#91D9F0"
!$TERNARY0300 = "#64C5E4" /' <- '/
!$TERNARY0400 = "#57ACC7"
!$TERNARY0500 = "#4792AA"
!$TERNARY0600 = "#33778D"
!$TERNARY0700 = "#205C70"
!$TERNARY0800 = "#104353"
!$TERNARY0900 = "#052A36"
!$TERNARY1000 = "#001319"

!$STATUS_RED0500 = "#FFF6F5"
!$STATUS_RED0100 = "#FFECEB"
!$STATUS_RED0200 = "#FFD3D1"
!$STATUS_RED0300 = "#FCB6B4"
!$STATUS_RED0400 = "#F59794"
!$STATUS_RED0500 = "#EF746F"
!$STATUS_RED0600 = "#E84C46"
!$STATUS_RED0700 = "#E22019" /' <- '/
!$STATUS_RED0800 = "#9F110B"
!$STATUS_RED0900 = "#5C0603"
!$STATUS_RED1000 = "#190100"

!$STATUS_GREEN0050 = "#F0FCF3"
!$STATUS_GREEN0100 = "#E1F8E7"
!$STATUS_GREEN0200 = "#C3E9CD"
!$STATUS_GREEN0300 = "#A4DBB2"
!$STATUS_GREEN0400 = "#84CC96"
!$STATUS_GREEN0500 = "#62BD79" /' <- '/
!$STATUS_GREEN0600 = "#469C5C"
!$STATUS_GREEN0700 = "#2B7C3F"
!$STATUS_GREEN0800 = "#155B26"
!$STATUS_GREEN0900 = "#063A13"
!$STATUS_GREEN1000 = "#001906"

!$STATUS_YELLOW0050 = "#FFFFE3"
!$STATUS_YELLOW0100 = "#FFFFC6"
!$STATUS_YELLOW0200 = "#FFF299"
!$STATUS_YELLOW0300 = "#FFE46A"
!$STATUS_YELLOW0400 = "#FFD637"
!$STATUS_YELLOW0500 = "#FFC700" /' <- '/
!$STATUS_YELLOW0600 = "#D1A507"
!$STATUS_YELLOW0700 = "#A38106"
!$STATUS_YELLOW0800 = "#755C03"
!$STATUS_YELLOW0900 = "#473800"
!$STATUS_YELLOW1000 = "#191400"

!$STATUS_ORANGE0050 = "#FFF7EF"
!$STATUS_ORANGE0100 = "#FFEEDE"
!$STATUS_ORANGE0200 = "#FFD7BE"
!$STATUS_ORANGE0300 = "#FFBE9B"
!$STATUS_ORANGE0400 = "#FCA374"
!$STATUS_ORANGE0500 = "#F78549"
!$STATUS_ORANGE0600 = "#F26419"
!$STATUS_ORANGE0700 = "#BC4C11"
!$STATUS_ORANGE0800 = "#863408"
!$STATUS_ORANGE0900 = "#501D02"
!$STATUS_ORANGE1000 = "#190900"

!$NEUTRAL0025 = "#F9F9F9"
!$NEUTRAL0050 = "#F2F3F4"
!$NEUTRAL0100 = "#E6E8E8"
!$NEUTRAL0200 = "#CCD0D1"
!$NEUTRAL0300 = "#B1B9BA"
!$NEUTRAL0400 = "#96A1A3"
!$NEUTRAL0500 = "#7A8A8C"
!$NEUTRAL0600 = "#5F7275"
!$NEUTRAL0700 = "#465B5E"
!$NEUTRAL0800 = "#2F4447"
!$NEUTRAL0900 = "#1C2E30"
!$NEUTRAL1000 = "#0D1819"

'' -----------------------------------------------------------------------------

!$BG_COLOR = $NEUTRAL0025
!$FG_COLOR = $NEUTRAL0800
!$TEXT = $NEUTRAL0800
!$REVERSE_TEXT = $NEUTRAL0025

!$SUCCESS = $STATUS_GREEN0500
!$DANGER = $STATUS_RED0700
!$WARNING = $STATUS_ORANG0500

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure $neutral_scheme()
	FontColor $NEUTRAL1000
	BorderColor $NEUTRAL0800
	BackgroundColor $NEUTRAL0050
    Shadowing 1.0

    '' Iris theming
    '' ---------------------------------
	FontColor<<iris>> $NEUTRAL0025
	BorderColor<<iris>> $NEUTRAL0025
	BackgroundColor<<iris>> $PRIMARY0600
!endprocedure


'' Default settings
'' -----------------------------------------------------------------------------

skinparam backgroundColor $BG_COLOR
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 16
skinparam defaultTextAlignment left
skinparam dpi 100
skinparam roundcorner 15


hide <<iris>> stereotype

'Controls how lines are drawn in PlantUML
'values: ortho, polyline, splines (default)
skinparam linetype polyline
' skinparam linetype ortho
' skinparam linetype splines

'Distance between elements (vertically, default: 30)
skinparam nodesep 40

'Distance between elements (horizontally, default: 30)
skinparam ranksep 40

'Controls the padding surrounding text
skinparam padding 8


'Line below ensures all classes have the same width in UML class diagram
'skinparam SameClassWidth true


'' Main element
'' -----------------------------------------------------------------------------

<style>

root {
    HyperLinkColor $SIGNATURE0600
    LineColor $NEUTRAL0800
    LineThickness 1
    FontColor $TEXT
    Margin 40
}

</style>


'' Single elements definitions
'' -----------------------------------------------------------------------------

skinparam component {
    $neutral_scheme()
}

skinparam database {
    $neutral_scheme()
}

skinparam rectangle {
    $neutral_scheme()
}

skinparam node {
    $neutral_scheme()
}

skinparam frame {
    $neutral_scheme()
}

skinparam actor {
    $neutral_scheme()
    Shadowing 0
}

''
'' Group definition should be placed *after* single elements definition
''

<style>

group {
    BackgroundColor $NEUTRAL0100
    Shadowing 0
}

</style>
